// server/src/constants/violationTypes.js
export const VIOLATION_CODES = {
  EXPIRED_METER: 'EXP_MTR_01',
  NO_PARKING_ZONE: 'NPZ_02',
  HANDICAP_UNAUTHORIZED: 'HND_03',
  FIRE_HYDRANT_BLOCK: 'FHD_04',
  DOUBLE_PARKING: 'DBL_05',
  BLOCKING_DRIVEWAY: 'BLK_DW_06',
  STREET_SWEEPING: 'ST_SWP_07',
  OVERTIME_LIMIT: 'OTL_08',
  BUS_LANE_BLOCK: 'BUS_LN_09',
  SIDEWALK_OBSTRUCTION: 'SDW_10'
};

export const VIOLATION_SEVERITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};
