// server/src/jobs/reportCleanupJob.js
import { logger } from '../utils/logger.js';

/**
 * Placeholder for periodic maintenance (e.g. purging generated report
 * export files from disk/object storage). No temporary files are
 * currently generated by this deployment, so this is a no-op that logs
 * its run rather than claiming to have cleaned something that doesn't
 * exist.
 */
export function runReportCleanupJob() {
  logger.debug('ReportCleanupJob: no temporary report artifacts to purge.');
}

export function startReportCleanupScheduler(intervalMs = 3600000) {
  return setInterval(runReportCleanupJob, intervalMs);
}
